import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

describe("standalone product", () => {
  it("does not depend on WechatOnCloud paths", () => {
    const compose = readFileSync(resolve(root, "docker-compose.yml"), "utf8");
    assert.doesNotMatch(compose, /\.\.\/wechat/);
    assert.doesNotMatch(compose, /woc-panel|woc-wx/);
    assert.match(compose, /build: \.\/docker/);
    assert.match(compose, /image:\s*ghcr\.io\/jingxuankang\/gpt-pro-cloud-desktop:latest/);
    assert.match(compose, /image:\s*ghcr\.io\/jingxuankang\/gpt-pro-cloud-gateway:latest/);
    assert.doesNotMatch(compose, /gpt-pro-cloud-desktop:local|gpt-pro-cloud-gateway:local/);
    assert.match(compose, /\.\/data\/a:\/config/);
    assert.match(compose, /\.\/data\/b:\/config/);
    assert.match(compose, /START_URL: \$\{START_URL:-https:\/\/chatgpt\.com\}/);
    assert.match(compose, /PROXY_URL_OVERRIDE: \$\{PROXY_URL_A:-\}/);
    const proxyInit = readFileSync(resolve(root, "docker/proxy-init.sh"), "utf8");
    assert.match(proxyInit, /PROXY_URL_OVERRIDE/);
    assert.ok(proxyInit.includes('RAW="${RAW//\\[::1\\]/host.docker.internal}"'));
    assert.equal(proxyInit.includes('RAW="${RAW//[::1]/host.docker.internal}"'), false);
    assert.doesNotMatch(compose, /9222|9223/);
    assert.doesNotMatch(compose, /ports:[\s\S]*debug/i);
    const up = readFileSync(resolve(root, "scripts/up.sh"), "utf8");
    assert.match(up, /docker compose pull/);
    assert.match(up, /docker compose up -d/);
    const happyPath = up.split("if ! docker compose pull")[0];
    assert.doesNotMatch(happyPath, /--build/);
    assert.match(up, /docker compose up -d --build/);
    assert.match(up, /ghcr\.io\/jingxuankang\/gpt-pro-cloud-gateway:latest/);
    assert.match(up, /ghcr\.io\/jingxuankang\/gpt-pro-cloud-desktop:latest/);
    for (const name of ["README.md", "README.zh-CN.md", "Deploy.md"]) {
      const doc = readFileSync(resolve(root, name), "utf8");
      assert.match(doc, /ghcr\.io\/jingxuankang\/gpt-pro-cloud-gateway:latest/);
      assert.match(doc, /docker compose pull/);
      assert.doesNotMatch(doc, /docker login/);
    }
  });

  it("proxy-init.sh rewrites [::1] without eating colons or digits", () => {
    const src = readFileSync(resolve(root, "docker/proxy-init.sh"), "utf8");
    const rewrites = src
      .split("\n")
      .map((l) => l.trim())
      .filter((l) => l.startsWith('RAW="${RAW//'));
    assert.equal(rewrites.length, 3);
    const run = (url) => {
      const script = ["RAW=$(cat)", ...rewrites, 'printf %s "$RAW"'].join("\n");
      return execFileSync("bash", ["-c", script], { encoding: "utf8", input: url });
    };
    assert.equal(run("http://127.0.0.1:7890"), "http://host.docker.internal:7890");
    assert.equal(run("socks5://warp:1080"), "socks5://warp:1080");
    assert.equal(run("http://[::1]:7890"), "http://host.docker.internal:7890");
    assert.equal(run("socks5://localhost:7891"), "socks5://host.docker.internal:7891");
  });

  it("desktop opens ChatGPT and honors rewritten proxy", () => {
    const start = readFileSync(resolve(root, "docker/autostart"), "utf8");
    const init = readFileSync(resolve(root, "docker/proxy-init.sh"), "utf8");
    assert.match(start, /--app="\$\{START_URL\}"/);
    const launch = start.slice(start.indexOf("/usr/bin/chromium"));
    assert.doesNotMatch(launch, /--kiosk/);
    assert.match(start, /No --kiosk/);
    assert.match(start, /X <= -1000/);
    assert.match(start, /--start-fullscreen/);
    assert.match(start, /--user-data-dir=\/config\/chromium/);
    assert.doesNotMatch(start, /user-data-dir=\/config\/chromium-/);
    assert.match(start, /--test-type/);
    assert.match(start, /--proxy-server=/);
    assert.match(start, /gpc-proxy-override/);
    assert.match(start, /ENABLE_CDP/);
    assert.match(start, /TAB_SEATS/);
    assert.match(start, /\.gpc-cdp/);
    assert.match(start, /CDP_ON/);
    assert.match(start, /\$\{CDP_FLAGS\}/);
    assert.match(start, /remote-debugging-port=9222/);
    assert.match(start, /remote-debugging-address=127.0.0.1/);
    assert.doesNotMatch(start, /remote-debugging-address=0.0.0.0/);
    assert.doesNotMatch(start, /^\s*--remote-debugging-port=9222/m);
    assert.doesNotMatch(start, /^python3 \/usr\/local\/bin\/gpc-cdp-fwd/m);
    assert.match(start, /sync_cdp_fwd/);
    assert.match(start, /gpc-cdp-fwd/);
    const fwd = readFileSync(resolve(root, "docker/cdp-fwd.py"), "utf8");
    assert.match(fwd, /ALLOWED_NAMES/);
    assert.match(fwd, /gpt-pro-cloud-gateway/);
    assert.match(init, /host\.docker\.internal/);
    const wm = readFileSync(resolve(root, "docker/update-autostart.sh"), "utf8");
    assert.match(wm, /gpc-no-chrome/);
    assert.match(wm, /<decor>no<\/decor>/);
    assert.match(wm, /<fullscreen>yes<\/fullscreen>/);
  });

  it("gateway is the only entry", () => {
    const gw = readFileSync(resolve(root, "gateway/server.mjs"), "utf8");
    assert.match(gw, /\/healthz/);
    assert.match(gw, /\/login/);
    assert.match(gw, /parseInstances/);
    assert.match(gw, /\/api\/login/);
    assert.match(gw, /\/api\/admin\/users/);
    const hide = readFileSync(resolve(root, "docker/hide-kasm.sh"), "utf8");
    assert.match(hide, /noVNC_logo/);
    assert.match(hide, /noVNC_transition/);
    const ui = readFileSync(resolve(root, "gateway/web/app.js"), "utf8");
    assert.match(ui, /\/vnc\/index\.html/);
    assert.match(ui, /seat-cast/);
    assert.match(ui, /\/seats\//);
    assert.match(ui, /deskMode/);
    assert.match(gw, /createSeatRegistry/);
    assert.match(gw, /startSeatScreencast/);
    assert.match(gw, /TAB_SEATS_MAX/);
    assert.match(gw, /createParkedChatGPTTab/);
    assert.doesNotMatch(gw, /probeDeskSession/);
    assert.doesNotMatch(gw, /withDeskCdp\(id, \(\) => createParkedChatGPTTab/);
    assert.doesNotMatch(gw, /withDeskCdp\(id, \(\) => runOnboard/);
    assert.match(gw, /forgetDeskBrowser/);
    assert.match(gw, /withDeskCdp/);
    assert.match(gw, /ONBOARD_YIELD_MS/);
    assert.match(gw, /deskCdpOn/);
    assert.match(gw, /applyDeskCdpLive/);
    assert.match(gw, /setDeskCdp/);
    assert.match(gw, /这个号未开多人分屏/);
    assert.match(gw, /页面协助需要开启调试口/);
    assert.match(ui, /clipboard_up=true/);
    assert.match(ui, /\/api\/desks\/\$\{id\}\/paste/);
    assert.match(ui, /\/api\/presence\/leave/);
    assert.match(ui, /noVNC_keyboardinput/);
    assert.match(ui, /clip-keys/);
    assert.match(ui, /\$\{MOD\}\+V/);
    assert.match(ui, /\/api\/desks\/\$\{id\}\/copy/);
    assert.match(ui, /\/api\/desks\/\$\{state\.deskId\}\/share/);
    assert.match(ui, /\/api\/desks\/\$\{id\}\/onboard/);
    assert.doesNotMatch(ui, /new-project|project-modal|新项目/);
    assert.match(gw, /18790\/grab/);
    assert.match(gw, /SHARE_CLICK/);
    assert.match(gw, /projectOnboardScript/);
    assert.match(gw, /waitForDesk/);
    assert.match(gw, /kickOnboard/);
    assert.match(gw, /deskCdpOn/);
    assert.match(gw, /\/api\/admin\/settings/);
    assert.match(ui, /data-cdp-toggle/);
    assert.match(ui, /允许多人同时使用/);
    assert.match(ui, /多人分屏/);
    assert.doesNotMatch(ui, /id="assist-toggle"/);
    assert.doesNotMatch(ui, /body: \{ assist:/);
    assert.match(gw, /readyOn/);
    assert.doesNotMatch(ui, /chromium 未就绪/);
    assert.match(gw, /projectDesk/);
    assert.match(gw, /\/onboard/);
    assert.match(gw, /18790/);
    assert.match(gw, /createLoginLimiter/);
    assert.match(gw, /createSessionStore/);
    assert.match(gw, /sessions\.json/);
    assert.match(gw, /content-security-policy/);
    assert.match(gw, /429/);
    assert.match(gw, /"PATCH"/);
    assert.match(gw, /deleteByUser/);
    assert.match(gw, /\/kick/);
    assert.match(gw, /kickLiveSession/);
    assert.match(gw, /createSocketHub/);
    assert.match(ui, /data-manage/);
    assert.match(ui, /"PATCH"/);
    assert.match(gw, /\/api\\\/admin\\\/desks/);
    assert.match(gw, /renameDesk/);
    assert.match(gw, /provisionDesk/);
    assert.match(gw, /retireDesk/);
    assert.match(gw, /removeDeskContainer/);
    assert.match(gw, /ensureDeskContainer/);
    assert.match(gw, /reconcileExtraDesks/);
    assert.match(ui, /data-rename/);
    assert.match(ui, /data-add-desk/);
    assert.match(ui, /data-delete/);
    assert.match(ui, /确定删除/);
    assert.match(ui, /\/api\/admin\/desks/);
    assert.match(ui, /正在启动/);
    const compose = readFileSync(resolve(root, "docker-compose.yml"), "utf8");
    assert.match(compose, /\/var\/run\/docker\.sock:\/var\/run\/docker\.sock/);
    assert.match(compose, /DESKTOP_TEMPLATE=gpt-pro-cloud-a/);
    assert.match(compose, /desktop-a/);
    assert.match(compose, /desktop-b/);
    assert.match(gw, /\/api\/setup/);
    assert.match(gw, /hasAdmin/);
    assert.match(ui, /创建管理员/);
    assert.match(gw, /setDeskProxy/);
    assert.match(gw, /setAllDeskProxies/);
    assert.match(gw, /applyDeskProxiesLive/);
    assert.match(gw, /\/api\/admin\/proxies/);
    assert.match(ui, /#\/settings/);
    assert.match(ui, /data-proxy-save/);
    assert.match(ui, /data-proxy-pick/);
    assert.match(ui, /id="proxy-all"/);
    assert.match(ui, /全部应用/);
    assert.match(ui, /data-assign/);
    assert.match(ui, /data-resetpw/);
    assert.match(ui, /data-toggle/);
    assert.match(ui, /断开/);
    assert.doesNotMatch(ui, /踢出去/);
    assert.match(ui, /data-kick-desk/);
    assert.match(ui, /occupancy/);
    assert.match(ui, /\/api\/admin\/users\/\$\{v\.id\}\/kick/);
    assert.match(ui, /assist-note/);
    assert.match(ui, /记忆隔离/);
    assert.match(ui, /仅项目内记忆/);
    assert.match(ui, /顶栏多一个「分享」/);
    assert.match(ui, /复制粘贴/);
    assert.match(ui, /开启后网关会连浏览器调试口/);
    assert.match(ui, /单人使用请保持关闭/);
    assert.match(ui, /短暂断开当前画面/);
    assert.match(ui, /ChatGPT 登录状态/);
    assert.doesNotMatch(ui, /无法检测|检测不到|undetectable/i);
    assert.doesNotMatch(ui, /老板号/);
    assert.doesNotMatch(ui, /互不可见/);
    assert.doesNotMatch(ui, /顶栏格子/);
    const assistStart = ui.indexOf('class="assist-note"');
    const assistBlock = ui.slice(assistStart, ui.indexOf("</section>", assistStart));
    assert.match(assistBlock, /记忆隔离/);
    assert.match(assistBlock, /记忆互不影响/);
    assert.match(assistBlock, /分屏席位/);
    assert.doesNotMatch(assistBlock, /复制粘贴/);
    const css = readFileSync(resolve(root, "gateway/web/app.css"), "utf8");
    assert.match(css, /\.cardgrid/);
    assert.match(css, /\.sec-head/);
    assert.match(css, /\.chip\.live/);
    assert.match(css, /\.status\.live/);
    assert.match(css, /\.acts/);
    assert.match(css, /\.assist-note/);
    assert.match(css, /\.seat-cast/);
    assert.doesNotMatch(css, /\.clip-note/);
    const zhReadme = readFileSync(resolve(root, "README.zh-CN.md"), "utf8");
    assert.doesNotMatch(zhReadme, /老板号/);
    assert.doesNotMatch(zhReadme, /互不可见/);
    assert.doesNotMatch(zhReadme, /顶栏格子/);
    const clipd = readFileSync(resolve(root, "docker/clipd.py"), "utf8");
    assert.match(clipd, /xclip/);
    assert.match(clipd, /image\//);
    assert.match(clipd, /\/proxy/);
    assert.match(clipd, /gpc-proxy-override/);
    assert.match(clipd, /\/cdp/);
    assert.match(clipd, /gpc-cdp/);
    assert.match(clipd, /kill_chromium/);
    assert.match(clipd, /CHROMIUM_KILL_PATTERNS/);
    assert.match(clipd, /\/usr\/lib\/chromium\/chromium/);
    assert.match(clipd, /user-data-dir=\/config\/chromium/);
    assert.doesNotMatch(clipd, /pkill.*\/usr\/bin\/chromium/);
    const chrome = readFileSync(resolve(root, "lib/chrome.mjs"), "utf8");
    assert.match(chrome, /waitForDesk/);
    assert.match(chrome, /TAB_CLIP_READ/);
    assert.match(chrome, /evaluateOnTarget/);
    assert.doesNotMatch(chrome, /webSocketDebuggerUrl/);
    const cdp = readFileSync(resolve(root, "lib/cdp.mjs"), "utf8");
    assert.match(cdp, /sessionFromProbe/);
    assert.match(cdp, /listDeskCookies/);
    assert.match(cdp, /probeDeskSession/);
    assert.match(cdp, /deskBrowserWs/);
    assert.match(cdp, /createDeskBrowserPool/);
    assert.match(cdp, /forgetDeskBrowser/);
    assert.match(cdp, /Target.getTargets/);
    assert.match(cdp, /createTargetViaHttp/);
    assert.match(cdp, /json\/new/);
    const fwd = readFileSync(resolve(root, "docker/cdp-fwd.py"), "utf8");
    assert.match(fwd, /PUT /);
    assert.match(fwd, /force_connection_close/);
    assert.match(fwd, /is_ws_upgrade/);
    assert.match(fwd, /close_pair/);
    assert.match(fwd, /select\.select/);
    const seats = readFileSync(resolve(root, "lib/seats.mjs"), "utf8");
    assert.match(seats, /DEFAULT_TAB_SEAT_CAP/);
    assert.match(seats, /targetsVisibleToSeat/);
    const gwPkg = readFileSync(resolve(root, "gateway/package.json"), "utf8");
    assert.match(gwPkg, /"ws"/);
    const readme = readFileSync(resolve(root, "README.md"), "utf8");
    assert.match(readme, /TAB_SEATS_MAX/);
    assert.match(readme, /Page.startScreencast/);
    assert.match(readme, /opt-in/i);
    assert.match(readme, /off by default/i);
    assert.doesNotMatch(readme, /second Chrome|second Docker|user-data-dir-\/config\/chromium-/i);
    const zh = readFileSync(resolve(root, "README.zh-CN.md"), "utf8");
    assert.match(zh, /默认关闭/);
    assert.match(zh, /调试口|CDP/);
    assert.match(chrome, /projectOnboardScript/);
    assert.match(chrome, /allowCreate/);
    assert.match(chrome, /inCreateForm/);
    assert.match(chrome, /New project/);
    assert.match(chrome, /project-only memory/);
    assert.match(chrome, /open project home/i);
    assert.match(chrome, /项目没有出现/);
  });
});
