import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

describe("standalone product", () => {
  it("does not depend on WechatOnCloud paths", () => {
    const compose = readFileSync(resolve(root, "docker-compose.yml"), "utf8");
    assert.doesNotMatch(compose, /\.\.\/wechat/);
    assert.doesNotMatch(compose, /woc-panel|woc-wx/);
    assert.match(compose, /build: \.\/docker/);
    assert.match(compose, /\.\/data\/a:\/config/);
    assert.match(compose, /\.\/data\/b:\/config/);
    assert.match(compose, /START_URL: \$\{START_URL:-https:\/\/chatgpt\.com\}/);
    assert.match(compose, /PROXY_URL_OVERRIDE: \$\{PROXY_URL_A:-\}/);
    const proxyInit = readFileSync(resolve(root, "docker/proxy-init.sh"), "utf8");
    assert.match(proxyInit, /PROXY_URL_OVERRIDE/);
    assert.doesNotMatch(compose, /9222|9223/);
  });

  it("desktop opens ChatGPT and honors rewritten proxy", () => {
    const start = readFileSync(resolve(root, "docker/autostart"), "utf8");
    const init = readFileSync(resolve(root, "docker/proxy-init.sh"), "utf8");
    assert.match(start, /--app="\$\{START_URL\}"/);
    assert.match(start, /--kiosk/);
    assert.match(start, /--start-fullscreen/);
    assert.match(start, /--test-type/);
    assert.match(start, /--user-data-dir=\/config\/chromium/);
    assert.match(start, /--proxy-server=/);
    assert.match(start, /gpc-proxy-override/);
    assert.match(start, /remote-debugging-port=9222/);
    assert.match(start, /remote-debugging-address=127.0.0.1/);
    assert.doesNotMatch(start, /remote-debugging-address=0.0.0.0/);
    assert.match(start, /gpc-cdp-fwd/);
    const fwd = readFileSync(resolve(root, "docker/cdp-fwd.py"), "utf8");
    assert.match(fwd, /ALLOWED_NAMES/);
    assert.match(fwd, /gpt-pro-cloud-gateway/);
    assert.match(init, /host\.docker\.internal/);
    const wm = readFileSync(resolve(root, "docker/update-autostart.sh"), "utf8");
    assert.match(wm, /gpc-no-chrome/);
    assert.match(wm, /<decor>no<\/decor>/);
    assert.match(wm, /<fullscreen>yes<\/fullscreen>/);
  });

  it("gateway is the only entry", () => {
    const gw = readFileSync(resolve(root, "gateway/server.mjs"), "utf8");
    assert.match(gw, /\/healthz/);
    assert.match(gw, /\/login/);
    assert.match(gw, /parseInstances/);
    assert.match(gw, /\/api\/login/);
    assert.match(gw, /\/api\/admin\/users/);
    const hide = readFileSync(resolve(root, "docker/hide-kasm.sh"), "utf8");
    assert.match(hide, /noVNC_logo/);
    assert.match(hide, /noVNC_transition/);
    const ui = readFileSync(resolve(root, "gateway/web/app.js"), "utf8");
    assert.match(ui, /\/vnc\/index\.html/);
    assert.match(ui, /clipboard_up=true/);
    assert.match(ui, /\/api\/desks\/\$\{id\}\/paste/);
    assert.match(ui, /\/api\/presence\/leave/);
    assert.match(ui, /noVNC_keyboardinput/);
    assert.match(ui, /clip-keys/);
    assert.match(ui, /\$\{MOD\}\+V/);
    assert.match(ui, /\/api\/desks\/\$\{id\}\/copy/);
    assert.match(ui, /\/api\/desks\/\$\{state\.deskId\}\/share/);
    assert.match(ui, /\/api\/desks\/\$\{id\}\/onboard/);
    assert.doesNotMatch(ui, /new-project|project-modal|新项目/);
    assert.match(gw, /18790\/grab/);
    assert.match(gw, /SHARE_CLICK/);
    assert.match(gw, /projectOnboardScript/);
    assert.match(gw, /waitForDesk/);
    assert.match(gw, /kickOnboard/);
    assert.match(gw, /assistOn/);
    assert.match(gw, /\/api\/admin\/settings/);
    assert.match(ui, /assist-toggle/);
    assert.match(ui, /页面协助/);
    assert.match(gw, /readyOn/);
    assert.doesNotMatch(ui, /chromium 未就绪/);
    assert.match(gw, /projectDesk/);
    assert.match(gw, /\/onboard/);
    assert.match(gw, /18790/);
    assert.match(gw, /createLoginLimiter/);
    assert.match(gw, /createSessionStore/);
    assert.match(gw, /sessions\.json/);
    assert.match(gw, /content-security-policy/);
    assert.match(gw, /429/);
    assert.match(gw, /"PATCH"/);
    assert.match(gw, /deleteByUser/);
    assert.match(ui, /data-manage/);
    assert.match(ui, /"PATCH"/);
    assert.match(gw, /\/api\\\/admin\\\/desks/);
    assert.match(gw, /renameDesk/);
    assert.match(gw, /provisionDesk/);
    assert.match(gw, /ensureDeskContainer/);
    assert.match(gw, /reconcileExtraDesks/);
    assert.match(ui, /data-rename/);
    assert.match(ui, /data-add-desk/);
    assert.match(ui, /\/api\/admin\/desks/);
    assert.match(ui, /正在启动/);
    const compose = readFileSync(resolve(root, "docker-compose.yml"), "utf8");
    assert.match(compose, /\/var\/run\/docker\.sock:\/var\/run\/docker\.sock/);
    assert.match(compose, /DESKTOP_TEMPLATE=gpt-pro-cloud-a/);
    assert.match(compose, /desktop-a/);
    assert.match(compose, /desktop-b/);
    assert.match(gw, /\/api\/setup/);
    assert.match(gw, /hasAdmin/);
    assert.match(ui, /创建管理员/);
    assert.match(gw, /setDeskProxy/);
    assert.match(ui, /#\/settings/);
    assert.match(ui, /data-proxy-save/);
    const clipd = readFileSync(resolve(root, "docker/clipd.py"), "utf8");
    assert.match(clipd, /xclip/);
    assert.match(clipd, /image\//);
    assert.match(clipd, /\/proxy/);
    assert.match(clipd, /gpc-proxy-override/);
    const chrome = readFileSync(resolve(root, "lib/chrome.mjs"), "utf8");
    assert.match(chrome, /waitForDesk/);
    assert.match(chrome, /projectOnboardScript/);
    assert.match(chrome, /allowCreate/);
    assert.match(chrome, /inCreateForm/);
    assert.match(chrome, /New project/);
    assert.match(chrome, /project-only memory/);
    assert.match(chrome, /open project home/i);
    assert.match(chrome, /项目没有出现/);
  });
});
